// Code generated by go2go; DO NOT EDIT.


//line ./code/generic/basic/demo1.go2:1
package main

//line ./code/generic/basic/demo1.go2:1
import (
	"fmt"
	"reflect"
)

//line ./code/generic/basic/demo1.go2:24
type StringType instantiate୦୦String୦string

//line ./code/generic/basic/demo1.go2:25
func main() {
//line ./code/generic/basic/demo1.go2:25
 instantiate୦୦Print୦string([]string{"Hello, ", "playground\n"})
//line ./code/generic/basic/demo1.go2:27
 a := StringType{str: "abc"}
	fmt.Println(a)
 fmt.Println(reflect.TypeOf(a).Name())
}

//line ./code/generic/basic/demo1.go2:29
type instantiate୦୦String୦string struct {
//line ./code/generic/basic/demo1.go2:21
 str string
}

//line ./code/generic/basic/demo1.go2:14
func instantiate୦୦Print୦string(s []string,) {
	for _, v := range s {
		fmt.Print(v)
	}
}

//line ./code/generic/basic/demo1.go2:18
type Importable୦ int

//line ./code/generic/basic/demo1.go2:18
var _ = fmt.Errorf
